### ISSUE TITLE
Traceback (most recent call last):   File "multiway/make_fragments.py", line 200, in <module>     run(config)   File "multiway/make_fragments.py", line 168, in run     if config["python_multi_threading"].lower() == "true": AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Feegooddddd** [XuyangBai/PointDSC#16]
when I run " python multiway/make_fragments.py redwood_simulated/livingroom1-simulated.json" , I meet the problem like above .Looking forward for your reply

**Comment by Feegooddddd** [comment]
Ok，I have solved it by myself
